# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'canvas.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Show(object):
    def setupUi(self, Show):
        Show.setObjectName("Show")
        Show.resize(480, 640)
        self.canvas = QtWidgets.QLabel(Show)
        self.canvas.setGeometry(QtCore.QRect(60, 30, 360, 480))
        self.canvas.setText("")
        self.canvas.setObjectName("canvas")
        self.widget = QtWidgets.QWidget(Show)
        self.widget.setGeometry(QtCore.QRect(60, 540, 361, 71))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.cancel = QtWidgets.QPushButton(self.widget)
        self.cancel.setMaximumSize(QtCore.QSize(80, 50))
        self.cancel.setObjectName("cancel")
        self.horizontalLayout.addWidget(self.cancel)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.confirm = QtWidgets.QPushButton(self.widget)
        self.confirm.setMaximumSize(QtCore.QSize(80, 50))
        self.confirm.setObjectName("confirm")
        self.horizontalLayout.addWidget(self.confirm)

        self.retranslateUi(Show)
        QtCore.QMetaObject.connectSlotsByName(Show)

    def retranslateUi(self, Show):
        _translate = QtCore.QCoreApplication.translate
        Show.setWindowTitle(_translate("Show", "Show"))
        self.cancel.setText(_translate("Show", "×"))
        self.confirm.setText(_translate("Show", "√"))
