# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(480, 640)
        font = QtGui.QFont()
        font.setFamily("等线 Light")
        Form.setFont(font)
        self.OpenImage = QtWidgets.QPushButton(Form)
        self.OpenImage.setGeometry(QtCore.QRect(165, 297, 150, 46))
        font = QtGui.QFont()
        font.setFamily("等线 Light")
        self.OpenImage.setFont(font)
        self.OpenImage.setObjectName("OpenImage")
        self.Path = QtWidgets.QLabel(Form)
        self.Path.setGeometry(QtCore.QRect(70, 360, 340, 41))
        self.Path.setText("")
        self.Path.setWordWrap(True)
        self.Path.setObjectName("Path")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(165, 440, 150, 46))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "mushroom"))
        self.OpenImage.setText(_translate("Form", "选取图片"))
        self.pushButton.setText(_translate("Form", "打开图片"))
